/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookstore.jooq.models.tables;


import com.sivalabs.bookstore.jooq.models.Keys;
import com.sivalabs.bookstore.jooq.models.Public;
import com.sivalabs.bookstore.jooq.models.tables.Orders.OrdersPath;
import com.sivalabs.bookstore.jooq.models.tables.records.OrderItemsRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderItems extends TableImpl<OrderItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.order_items</code>
     */
    public static final OrderItems ORDER_ITEMS = new OrderItems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderItemsRecord> getRecordType() {
        return OrderItemsRecord.class;
    }

    /**
     * The column <code>public.order_items.id</code>.
     */
    public final TableField<OrderItemsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.order_items.code</code>.
     */
    public final TableField<OrderItemsRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.order_items.name</code>.
     */
    public final TableField<OrderItemsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.order_items.price</code>.
     */
    public final TableField<OrderItemsRecord, BigDecimal> PRICE = createField(DSL.name("price"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.order_items.quantity</code>.
     */
    public final TableField<OrderItemsRecord, Integer> QUANTITY = createField(DSL.name("quantity"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.order_items.order_id</code>.
     */
    public final TableField<OrderItemsRecord, Long> ORDER_ID = createField(DSL.name("order_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private OrderItems(Name alias, Table<OrderItemsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OrderItems(Name alias, Table<OrderItemsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.order_items</code> table reference
     */
    public OrderItems(String alias) {
        this(DSL.name(alias), ORDER_ITEMS);
    }

    /**
     * Create an aliased <code>public.order_items</code> table reference
     */
    public OrderItems(Name alias) {
        this(alias, ORDER_ITEMS);
    }

    /**
     * Create a <code>public.order_items</code> table reference
     */
    public OrderItems() {
        this(DSL.name("order_items"), null);
    }

    public <O extends Record> OrderItems(Table<O> path, ForeignKey<O, OrderItemsRecord> childPath, InverseForeignKey<O, OrderItemsRecord> parentPath) {
        super(path, childPath, parentPath, ORDER_ITEMS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OrderItemsPath extends OrderItems implements Path<OrderItemsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OrderItemsPath(Table<O> path, ForeignKey<O, OrderItemsRecord> childPath, InverseForeignKey<O, OrderItemsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OrderItemsPath(Name alias, Table<OrderItemsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OrderItemsPath as(String alias) {
            return new OrderItemsPath(DSL.name(alias), this);
        }

        @Override
        public OrderItemsPath as(Name alias) {
            return new OrderItemsPath(alias, this);
        }

        @Override
        public OrderItemsPath as(Table<?> alias) {
            return new OrderItemsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<OrderItemsRecord, Long> getIdentity() {
        return (Identity<OrderItemsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrderItemsRecord> getPrimaryKey() {
        return Keys.ORDER_ITEMS_PKEY;
    }

    @Override
    public List<ForeignKey<OrderItemsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ORDER_ITEMS__ORDER_ITEMS_ORDER_ID_FKEY);
    }

    private transient OrdersPath _orders;

    /**
     * Get the implicit join path to the <code>public.orders</code> table.
     */
    public OrdersPath orders() {
        if (_orders == null)
            _orders = new OrdersPath(this, Keys.ORDER_ITEMS__ORDER_ITEMS_ORDER_ID_FKEY, null);

        return _orders;
    }

    @Override
    public OrderItems as(String alias) {
        return new OrderItems(DSL.name(alias), this);
    }

    @Override
    public OrderItems as(Name alias) {
        return new OrderItems(alias, this);
    }

    @Override
    public OrderItems as(Table<?> alias) {
        return new OrderItems(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderItems rename(String name) {
        return new OrderItems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderItems rename(Name name) {
        return new OrderItems(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderItems rename(Table<?> name) {
        return new OrderItems(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItems where(Condition condition) {
        return new OrderItems(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItems where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItems where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItems where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderItems where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderItems where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderItems where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderItems where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItems whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItems whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
