/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookstore.jooq.models.tables.records;


import com.sivalabs.bookstore.jooq.models.tables.Orders;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.orders.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.orders.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.orders.order_number</code>.
     */
    public void setOrderNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.orders.order_number</code>.
     */
    public String getOrderNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.orders.customer_name</code>.
     */
    public void setCustomerName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.orders.customer_name</code>.
     */
    public String getCustomerName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.orders.customer_email</code>.
     */
    public void setCustomerEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.orders.customer_email</code>.
     */
    public String getCustomerEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.orders.customer_phone</code>.
     */
    public void setCustomerPhone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.orders.customer_phone</code>.
     */
    public String getCustomerPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.orders.delivery_address_line1</code>.
     */
    public void setDeliveryAddressLine1(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.orders.delivery_address_line1</code>.
     */
    public String getDeliveryAddressLine1() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.orders.delivery_address_line2</code>.
     */
    public void setDeliveryAddressLine2(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.orders.delivery_address_line2</code>.
     */
    public String getDeliveryAddressLine2() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.orders.delivery_address_city</code>.
     */
    public void setDeliveryAddressCity(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.orders.delivery_address_city</code>.
     */
    public String getDeliveryAddressCity() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.orders.delivery_address_state</code>.
     */
    public void setDeliveryAddressState(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.orders.delivery_address_state</code>.
     */
    public String getDeliveryAddressState() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.orders.delivery_address_zip_code</code>.
     */
    public void setDeliveryAddressZipCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.orders.delivery_address_zip_code</code>.
     */
    public String getDeliveryAddressZipCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.orders.delivery_address_country</code>.
     */
    public void setDeliveryAddressCountry(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.orders.delivery_address_country</code>.
     */
    public String getDeliveryAddressCountry() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.orders.status</code>.
     */
    public void setStatus(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.orders.status</code>.
     */
    public String getStatus() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.orders.comments</code>.
     */
    public void setComments(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.orders.comments</code>.
     */
    public String getComments() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.orders.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.orders.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>public.orders.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.orders.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(Long id, String orderNumber, String customerName, String customerEmail, String customerPhone, String deliveryAddressLine1, String deliveryAddressLine2, String deliveryAddressCity, String deliveryAddressState, String deliveryAddressZipCode, String deliveryAddressCountry, String status, String comments, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Orders.ORDERS);

        setId(id);
        setOrderNumber(orderNumber);
        setCustomerName(customerName);
        setCustomerEmail(customerEmail);
        setCustomerPhone(customerPhone);
        setDeliveryAddressLine1(deliveryAddressLine1);
        setDeliveryAddressLine2(deliveryAddressLine2);
        setDeliveryAddressCity(deliveryAddressCity);
        setDeliveryAddressState(deliveryAddressState);
        setDeliveryAddressZipCode(deliveryAddressZipCode);
        setDeliveryAddressCountry(deliveryAddressCountry);
        setStatus(status);
        setComments(comments);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
