/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookstore.jooq.models.tables.records;


import com.sivalabs.bookstore.jooq.models.tables.OrderItems;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderItemsRecord extends UpdatableRecordImpl<OrderItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.order_items.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.order_items.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.order_items.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.order_items.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.order_items.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.order_items.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.order_items.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.order_items.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.order_items.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.order_items.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.order_items.order_id</code>.
     */
    public void setOrderId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.order_items.order_id</code>.
     */
    public Long getOrderId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderItemsRecord
     */
    public OrderItemsRecord() {
        super(OrderItems.ORDER_ITEMS);
    }

    /**
     * Create a detached, initialised OrderItemsRecord
     */
    public OrderItemsRecord(Long id, String code, String name, BigDecimal price, Integer quantity, Long orderId) {
        super(OrderItems.ORDER_ITEMS);

        setId(id);
        setCode(code);
        setName(name);
        setPrice(price);
        setQuantity(quantity);
        setOrderId(orderId);
        resetChangedOnNotNull();
    }
}
