/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookstore.jooq.models.tables.records;


import com.sivalabs.bookstore.jooq.models.tables.Products;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductsRecord extends UpdatableRecordImpl<ProductsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.products.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.products.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.products.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.products.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.products.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.products.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.products.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.products.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.products.image_url</code>.
     */
    public void setImageUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.products.image_url</code>.
     */
    public String getImageUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.products.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.products.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductsRecord
     */
    public ProductsRecord() {
        super(Products.PRODUCTS);
    }

    /**
     * Create a detached, initialised ProductsRecord
     */
    public ProductsRecord(Long id, String code, String name, String description, String imageUrl, BigDecimal price) {
        super(Products.PRODUCTS);

        setId(id);
        setCode(code);
        setName(name);
        setDescription(description);
        setImageUrl(imageUrl);
        setPrice(price);
        resetChangedOnNotNull();
    }
}
